import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
	{
		_id: uuid(),
		title: "Steve Jobs",
		author: "by Walter Isaacson",
		price: "360",
		previousPrice: "400",
		image: "/assets/productImages/stevejobs.webp",
		categoryName: "Biographies",
		rating: 5,
	},
	{
		_id: uuid(),
		title: "GrandParents",
		author: "by Sudha Murty",
		price: "380",
		previousPrice: "420",
		image: "/assets/productImages/grandparents.webp",
		categoryName: "Children-Books",
		rating: 1.4,
	},
	{
		_id: uuid(),
		title: "Do Epic Shit",
		author: "by Ankur Wariko",
		price: "250",
		previousPrice: "320",
		image: "/assets/productImages/doepicshit.webp",
		categoryName: "New-Releases",
		rating: 4.6,
	},
	{
		_id: uuid(),
		title: "Dune",
		author: "by Frank Herbert",
		price: "500",
		previousPrice: "620",
		image: "/assets/productImages/dune.webp",
		categoryName: "Fiction",
		rating: 1.4,
	},
	{
		_id: uuid(),
		title: "Attitude",
		author: "by keller Jef",
		price: "500",
		previousPrice: "620",
		image: "/assets/productImages/attitude.webp",
		categoryName: "Self-Help",
		rating: 3,
	},

	{
		_id: uuid(),
		title: "Wings of Fire",
		author: "by Arun Tiwari",
		price: "160",
		previousPrice: "200",
		image: "/assets/productImages/wings.webp",
		categoryName: "Biographies",
		rating: 4,
	},
	{
		_id: uuid(),
		title: "Call for IIMs",
		author: "by Trishna Chatterjee",
		price: "700",
		previousPrice: "720",
		image: "/assets/productImages/iims.webp",
		categoryName: "New-Releases",
		rating: 2.6,
	},
	{
		_id: uuid(),
		title: "Think Like Monk",
		author: "by Jay Shetty",
		price: "400",
		previousPrice: "420",
		image: "/assets/productImages/think.webp",
		categoryName: "Self-Help",
		rating: 4,
	},
	{
		_id: uuid(),
		title: "Elon Musk",
		author: "by Ashlee vance",
		price: "580",
		previousPrice: "700",
		image: "/assets/productImages/elon.webp",
		categoryName: "Biographies",
		rating: 4,
	},
	{
		_id: uuid(),
		title: "Three Thousand",
		author: "by Sudha Murty",
		price: "300",
		previousPrice: "320",
		image: "/assets/productImages/three.webp",
		categoryName: "Children-Books",
		rating: 4.4,
	},

	{
		_id: uuid(),
		title: "Stories",
		author: "by Gaurav Modi",
		price: "150",
		previousPrice: "220",
		image: "/assets/productImages/stories.webp",
		categoryName: "New-Releases",
		rating: 3.6,
	},
	{
		_id: uuid(),
		title: "Life Amazing",
		author: "by Gopal Das",
		price: "400",
		previousPrice: "420",
		image: "/assets/productImages/life.webp",
		categoryName: "Self-Help",
		rating: 5,
	},
	{
		_id: uuid(),
		title: "Blue umbrella",
		author: "by Ruskin Bond",
		price: "80",
		previousPrice: "120",
		image: "/assets/productImages/blue.webp",
		categoryName: "Fiction",
		rating: 1,
	},
	{
		_id: uuid(),
		title: "Skill It",
		author: "by Ronnie",
		price: "200",
		previousPrice: "320",
		image: "/assets/productImages/skill.webp",
		categoryName: "Self-Help",
		rating: 3.5,
	},
	{
		_id: uuid(),
		title: "Old Man",
		author: "by Sudha Murty",
		price: "400",
		previousPrice: "520",
		image: "/assets/productImages/old.webp",
		categoryName: "Children-Books",
		rating: 3.4,
	},
	{
		_id: uuid(),
		title: "10X Rule",
		author: "by Cardone Grant",
		price: "350",
		previousPrice: "420",
		image: "/assets/productImages/10.webp",
		categoryName: "New-Releases",
		rating: 3.6,
	},
	{
		_id: uuid(),
		title: "You can win",
		author: "by khera Shiv",
		price: "500",
		previousPrice: "820",
		image: "/assets/productImages/you.webp",
		categoryName: "Self-Help",
		rating: 5,
	},
	{
		_id: uuid(),
		title: "You've Reached",
		author: "by Dustin Thao",
		price: "350",
		previousPrice: "430",
		image: "/assets/productImages/you.webp",
		categoryName: "New-Releases",
		rating: 1.6,
	},
	{
		_id: uuid(),
		title: "Master",
		author: "by Sandeep Sharma",
		price: "600",
		previousPrice: "720",
		image: "/assets/productImages/master.webp",
		categoryName: "Self-Help",
		rating: 1.5,
	},
	{
		_id: uuid(),
		title: "Great Stories",
		author: "by Ruskin Bond",
		price: "500",
		previousPrice: "520",
		image: "/assets/productImages/great.webp",
		categoryName: "Children-Books",
		rating: 2.4,
	},
	{
		_id: uuid(),
		title: "Birds of Fray",
		author: "by Rajat Narang",
		price: "650",
		previousPrice: "700",
		image: "/assets/productImages/birds.webp",
		categoryName: "New-Releases",
		rating: 3.6,
	},
	{
		_id: uuid(),
		title: "The Dhoni Touch",
		author: "by Bharat Sundaresan",
		price: "880",
		previousPrice: "900",
		image: "/assets/productImages/dhoni.webp",
		categoryName: "Biographies",
		rating: 3,
	},
	{
		_id: uuid(),
		title: "Atomic Habbits",
		author: "by James Clear",
		price: "600",
		previousPrice: "620",
		image: "/assets/productImages/atomic.webp",
		categoryName: "Self-Help",
		rating: 5,
	},

	{
		_id: uuid(),
		title: "The Gruffalo",
		author: "by Julia",
		price: "200",
		previousPrice: "320",
		image: "/assets/productImages/gruffalo.webp",
		categoryName: "Children-Books",
		rating: 3.4,
	},
	{
		_id: uuid(),
		title: "The Archer",
		author: "by Coelho Paulo",
		price: "280",
		previousPrice: "720",
		image: "/assets/productImages/archer.webp",
		categoryName: "Fiction",
		rating: 4.4,
	},
	{
		_id: uuid(),
		title: "Teaching",
		author: "by Janaka ",
		price: "450",
		previousPrice: "530",
		image: "/assets/productImages/teaching.webp",
		categoryName: "New-Releases",
		rating: 4,
	},
	{
		_id: uuid(),
		title: "Little Owl",
		author: "by Gliori Debi",
		price: "600",
		previousPrice: "720",
		image: "/assets/productImages/little.webp",
		categoryName: "Children-Books",
		rating: 3.4,
	},
	{
		_id: uuid(),
		title: "Deep Work",
		author: "by Cal Newport",
		price: "400",
		previousPrice: "520",
		image: "/assets/productImages/work.webp",
		categoryName: "Self-Help",
		rating: 3,
	},
	{
		_id: uuid(),
		title: "Almanacy of NR",
		author: "by Eric",
		price: "600",
		previousPrice: "720",
		image: "/assets/productImages/navalravikant.webp",
		categoryName: "Self-Help",
		rating: 5,
	},
	{
		_id: uuid(),
		title: "1984",
		author: "by George Orwell",
		price: "180",
		previousPrice: "220",
		image: "/assets/productImages/1984.webp",
		categoryName: "Fiction",
		rating: 4.4,
	},
	{
		_id: uuid(),
		title: "Unfinished",
		author: "by Priyanka Chopra",
		price: "980",
		previousPrice: "1000",
		image: "/assets/productImages/unfinished.webp",
		categoryName: "Biographies",
		rating: 4.5,
	},
	{
		_id: uuid(),
		title: "Eat that Frog",
		author: "by Brian Tracy",
		price: "300",
		previousPrice: "420",
		image: "/assets/productImages/frog.webp",
		categoryName: "Self-Help",
		rating: 3,
	},
	{
		_id: uuid(),
		title: "Fifth Mountain",
		author: "by Coelho Paulo",
		price: "480",
		previousPrice: "620",
		image: "/assets/productImages/fifth.webp",
		categoryName: "Fiction",
		rating: 3.4,
	},
	{
		_id: uuid(),
		title: "Sometimes",
		author: "by Nayar Nandini",
		price: "300",
		previousPrice: "420",
		image: "/assets/productImages/mama.webp",
		categoryName: "Children-Books",
		rating: 2,
	},
	{
		_id: uuid(),
		title: "Becoming",
		author: "by Michelle Obama",
		price: "580",
		previousPrice: "700",
		image: "/assets/productImages/becoming.webp",
		categoryName: "Biographies",
		rating: 2.5,
	},
	{
		_id: uuid(),
		title: "Belive",
		author: "by Bharat Sundaresan",
		price: "280",
		previousPrice: "400",
		image: "/assets/productImages/believe.webp",
		categoryName: "Biographies",
		rating: 1.5,
	},
	{
		_id: uuid(),
		title: "Hooked",
		author: "by Nir Eyal ",
		price: "550",
		previousPrice: "630",
		image: "/assets/productImages/hooked.webp",
		categoryName: "New-Releases",
		rating: 3,
	},
	{
		_id: uuid(),
		title: "Sherlock Homes",
		author: "by Doyle Conan",
		price: "980",
		previousPrice: "1000",
		image: "/assets/productImages/sherlock.webp",
		categoryName: "Fiction",
		rating: 4.4,
	},
	{
		_id: uuid(),
		title: "It's ok",
		author: "by Prachi Gupta",
		price: "150",
		previousPrice: "230",
		image: "/assets/productImages/itsok.webp",
		categoryName: "New-Releases",
		rating: 4,
	},
	{
		_id: uuid(),
		title: "Aesop's Fables",
		author: "by Aesop",
		price: "500",
		previousPrice: "620",
		image: "/assets/productImages/fables.webp",
		categoryName: "Children-Books",
		rating: 4,
	},
	{
		_id: uuid(),
		title: "Treasure Island",
		author: "by Stevenson Robert ",
		price: "370",
		previousPrice: "440",
		image: "/assets/productImages/island.webp",
		categoryName: "Fiction",
		rating: 3.4,
	},
	{
		_id: uuid(),
		title: "One Indian Girl",
		author: "by Chetan Bhagat",
		price: "250",
		previousPrice: "320",
		image: "/assets/productImages/one.webp",
		categoryName: "Fiction",
		rating: 3,
	},
	{
		_id: uuid(),
		title: "Let me Say it",
		author: "by Maria Rakesh",
		price: "280",
		previousPrice: "400",
		image: "/assets/productImages/letme.webp",
		categoryName: "Biographies",
		rating: 1.5,
	},
	{
		_id: uuid(),
		title: "3 Little Pigs",
		author: "by Davidson",
		price: "260",
		previousPrice: "340",
		image: "/assets/productImages/pigs.webp",
		categoryName: "Children-Books",
		rating: 4,
	},
	{
		_id: uuid(),
		title: "Harry Potter Set",
		author: "by JK Rowling",
		price: "950",
		previousPrice: "980",
		image: "/assets/productImages/harry.webp",
		categoryName: "Fiction",
		rating: 5,
	},
	{
		_id: uuid(),
		title: "400",
		author: "by Chetan Bhagat",
		price: "120",
		previousPrice: "180",
		image: "/assets/productImages/400.webp",
		categoryName: "Fiction",
		rating: 2,
	},
	{
		_id: uuid(),
		title: "The Diary of",
		author: "by Anne Frank",
		price: "180",
		previousPrice: "200",
		image: "/assets/productImages/diary.webp",
		categoryName: "Biographies",
		rating: 4.5,
	},
	{
		_id: uuid(),
		title: "The Alchemist",
		author: "by Coelho Paulo",
		price: "280",
		previousPrice: "340",
		image: "/assets/productImages/the.webp",
		categoryName: "Fiction",
		rating: 4.4,
	},
	{
		_id: uuid(),
		title: "Zoo",
		author: "by Mairi",
		price: "660",
		previousPrice: "840",
		image: "/assets/productImages/zoo.webp",
		categoryName: "Children-Books",
		rating: 5,
	},
	{
		_id: uuid(),
		title: "Silent Patient",
		author: "by Alex",
		price: "670",
		previousPrice: "740",
		image: "/assets/productImages/silent.webp",
		categoryName: "Fiction",
		rating: 3.4,
	},
	{
		_id: uuid(),
		title: "Ratan Tata",
		author: "by Adarsh Kumar",
		price: "180",
		previousPrice: "200",
		image: "/assets/productImages/tata.webp",
		categoryName: "Biographies",
		rating: 4.5,
	},
	{
		_id: uuid(),
		title: "NDA",
		author: "by Omkar Grant",
		price: "350",
		previousPrice: "420",
		image: "/assets/productImages/nda.webp",
		categoryName: "New-Releases",
		rating: 3.6,
	},
];
