import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
	{
		_id: uuid(),
		title: "Steve Jobs",
		author: "by Walter Isaacson",
		price: "360",
		previousPrice: "400",
		image: "/assets/productImages/Biography.jpg",
		categoryName: "Biographies",
		rating: 5,
	},
	{
		_id: uuid(),
		title: "GrandParents",
		author: "by Sudha Murty",
		price: "380",
		previousPrice: "420",
		image: "/assets/productImages/childrens.jpg",
		categoryName: "Children-Books",
		rating: 1.4,
	},
	{
		_id: uuid(),
		title: "Dune",
		author: "by Frank Herbert",
		price: "500",
		previousPrice: "620",
		image: "/assets/productImages/fiction.jpg",
		categoryName: "Fiction",
		rating: 1.4,
	},
	{
		_id: uuid(),
		title: "Do Epic Shit",
		author: "by Ankur Wariko",
		price: "250",
		previousPrice: "320",
		image: "/assets/productImages/newrelease.jpg",
		categoryName: "New-Releases",
		rating: 4.6,
	},
	{
		_id: uuid(),
		title: "Almanacy of NR",
		author: "by Eric",
		price: "600",
		previousPrice: "720",
		image: "/assets/productImages/naval_book.jpg",
		categoryName: "Self-Help",
		rating: 5,
	},
	{
		_id: uuid(),
		title: "Steve Jobs",
		author: "by Walter Isaacson",
		price: "360",
		previousPrice: "400",
		image: "/assets/productImages/Biography.jpg",
		categoryName: "Biographies",
		rating: 4.8,
	},
	{
		_id: uuid(),
		title: "GrandParents",
		author: "by Sudha Murty",
		price: "380",
		previousPrice: "420",
		image: "/assets/productImages/childrens.jpg",
		categoryName: "Children-Books",
		rating: 2,
	},
	{
		_id: uuid(),
		title: "Dune",
		author: "by Frank Herbert",
		price: "500",
		previousPrice: "620",
		image: "/assets/productImages/fiction.jpg",
		categoryName: "Fiction",
		rating: 1,
	},
	{
		_id: uuid(),
		title: "Do Epic Shit",
		author: "by Ankur Wariko",
		price: "250",
		previousPrice: "320",
		image: "/assets/productImages/newrelease.jpg",
		categoryName: "New-Releases",
		rating: 5,
	},
	{
		_id: uuid(),
		title: "Almanacy of NR",
		author: "by Eric",
		price: "600",
		previousPrice: "720",
		image: "/assets/productImages/naval_book.jpg",
		categoryName: "Self-Help",
		rating: 4,
	},
	{
		_id: uuid(),
		title: "Steve Jobs",
		author: "by Walter Isaacson",
		price: "360",
		previousPrice: "400",
		image: "/assets/productImages/Biography.jpg",
		categoryName: "Biographies",
		rating: 5,
	},
	{
		_id: uuid(),
		title: "GrandParents",
		author: "by Sudha Murty",
		price: "380",
		previousPrice: "420",
		image: "/assets/productImages/childrens.jpg",
		categoryName: "Children-Books",
		rating: 1,
	},
	{
		_id: uuid(),
		title: "Dune",
		author: "by Frank Herbert",
		price: "500",
		previousPrice: "620",
		image: "/assets/productImages/fiction.jpg",
		categoryName: "Fiction",
		rating: 2,
	},
	{
		_id: uuid(),
		title: "Do Epic Shit",
		author: "by Ankur Wariko",
		price: "250",
		previousPrice: "320",
		image: "/assets/productImages/newrelease.jpg",
		categoryName: "New-Releases",
		rating: 4,
	},
	{
		_id: uuid(),
		title: "Almanacy of NR",
		author: "by Eric",
		price: "600",
		previousPrice: "720",
		image: "/assets/productImages/naval_book.jpg",
		categoryName: "Self-Help",
		rating: 3,
	},
];
