export const userActions = {
	GET_USER: "GET_USER",
	EDIT_USER: "EDIT_USER",
	GET_ADDRESS: "GET_ADDRESS",
	ADD_ADDRESS: "ADD_ADDRESS",
	EDIT_ADDRESS: "EDIT_ADDRESS",
	DELETE_ADDRESS: "DELETE_ADDRESS",
};
