export const filterAction = {
	SORT_BY_PRICE: "SORT_BY_PRICE",
	PRICE_RANGE: "PRICE_RANGE",
	FILTER_BY_CATEGORY: "FILTER_BY_CATEGORY",
	FILTER_BY_RATINGS: "FILTER_BY_RATINGS",
	SEARCH_QUERY: "SEARCH_QUERY",
};
